import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { Archive, AudioLines, Bold, Check, CheckSquare, ChevronLeft, ChevronDown, Clock3, Command, Download, Eraser, FileDown, FileText, Filter, Grid2X2, ImagePlus, Italic, Link2, List, Loader2, Mail, MapPin, Menu, Mic, MoreHorizontal, Palette, Pin, Plus, Printer, Search, Send, Share2, Square, Tag, Trash2, Underline, Upload, X } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { cn } from '@/lib/utils';

type NoteType='text'|'checklist'|'image'|'drawing'|'audio';
type Color='default'|'warm'|'yellow'|'green'|'blue'|'purple'|'pink'|'red';
type Note={id:string;user_id:string;title:string;content:string;note_type:NoteType;color:Color;is_pinned:boolean;is_archived:boolean;is_deleted:boolean;deleted_at:string|null;reminder_at:string|null;created_at:string;updated_at:string;sort_order:number;ocr_text:string;transcript:string;metadata:Record<string,unknown>};
type Label={id:string;user_id:string;name:string;color:Color};
type Checklist={id:string;note_id:string;parent_id:string|null;title:string;is_completed:boolean;position:number};
type Attachment={id:string;note_id:string;user_id:string;attachment_type:'image'|'audio'|'drawing'|'file';file_path:string|null;file_name:string;mime_type:string;size_bytes:number;transcript:string;signed_url?:string};
type Reminder={id:string;note_id:string;user_id:string;reminder_type:'datetime'|'location';remind_at:string|null;location_lat:number|null;location_lng:number|null;location_radius_m:number|null;location_trigger:'arrive'|'leave'|null;repeat_rule:string|null;title:string;completed_at:string|null};
const colorOptions:{key:Color;label:string;hex:string}[]=[{key:'default',label:'Neutro',hex:'#eeeeec'},{key:'warm',label:'Areia',hex:'#f4e5d2'},{key:'yellow',label:'Amarelo',hex:'#fff2ad'},{key:'green',label:'Verde',hex:'#dcefdc'},{key:'blue',label:'Azul',hex:'#dceafb'},{key:'purple',label:'Lilás',hex:'#e9e1f5'},{key:'pink',label:'Rosa',hex:'#f5dfe7'},{key:'red',label:'Coral',hex:'#f3ddd7'}];
const types:{key:NoteType;label:string;icon:any}[]=[{key:'text',label:'Texto',icon:FileText},{key:'checklist',label:'Checklist',icon:CheckSquare},{key:'image',label:'Imagem',icon:ImagePlus},{key:'drawing',label:'Desenho',icon:Palette},{key:'audio',label:'Áudio',icon:AudioLines}];
const plain=(s:string)=>s.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const download=(b:Blob,n:string)=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)};
const meters=(a:{lat:number,lng:number},b:{lat:number,lng:number})=>{const p=Math.PI/180,R=6371000,dl=(b.lat-a.lat)*p,dn=(b.lng-a.lng)*p,x=Math.sin(dl/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dn/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};

export function NotesPage(){
  const {user}=useAuth();
  const [notes,setNotes]=useState<Note[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|'pinned'|'archive'|'trash'>('all'),[view,setView]=useState<'grid'|'list'>('grid');
  const [typeFilter,setTypeFilter]=useState<NoteType|'all'>('all'),[colorFilter,setColorFilter]=useState<Color|'all'>('all'),[labelFilter,setLabelFilter]=useState('all'),[reminderFilter,setReminderFilter]=useState('all'),[filters,setFilters]=useState(false);
  const [labels,setLabels]=useState<Label[]>([]),[links,setLinks]=useState<Record<string,string[]>>({}),[check,setCheck]=useState<Record<string,Checklist[]>>({}),[files,setFiles]=useState<Record<string,Attachment[]>>({}),[reminders,setReminders]=useState<Reminder[]>([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[newMenu,setNewMenu]=useState(false),[more,setMore]=useState(false),[share,setShare]=useState(false),[reminder,setReminder]=useState(false),[labelPanel,setLabelPanel]=useState(false),[theme,setTheme]=useState<'system'|'light'|'dark'>((localStorage.getItem('notes-theme') as any)||'system'),[systemDark,setSystemDark]=useState(window.matchMedia('(prefers-color-scheme: dark)').matches);
  const [shareEmail,setShareEmail]=useState(''),[newLabel,setNewLabel]=useState(''),[remindAt,setRemindAt]=useState(''),[repeat,setRepeat]=useState('none'),[locationTrigger,setLocationTrigger]=useState<'arrive'|'leave'>('arrive'),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[drawTool,setDrawTool]=useState<'pen'|'marker'|'eraser'>('pen');
  const editorRef=useRef<HTMLDivElement|null>(null),canvasRef=useRef<HTMLCanvasElement|null>(null),mediaRef=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),speech=useRef<any>(null),timerRef=useRef<number|null>(null),saveRef=useRef<number|null>(null);
  const selected=notes.find(n=>n.id===selectedId)??null,dark=theme==='dark'||(theme==='system'&&systemDark);

  useEffect(()=>{if(user)void load()},[user]);
  useEffect(()=>{localStorage.setItem('notes-theme',theme)},[theme]);
  useEffect(()=>{const m=window.matchMedia('(prefers-color-scheme: dark)'),f=()=>setSystemDark(m.matches);m.addEventListener?.('change',f);return()=>m.removeEventListener?.('change',f)},[]);
  useEffect(()=>{if(!selected)return;setMore(false);setShare(false);setReminder(false);setLabelPanel(false);void loadSelected(selected.id)},[selectedId]);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('notes-search')?.focus()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='n'){e.preventDefault();void create('text')}if(e.key==='Escape')setSelectedId(null)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[]);
  useEffect(()=>{if(!user)return;const c=supabase.channel('notes-realtime-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'notes'},p=>{if(p.eventType==='INSERT'){const n=p.new as Note;if(n.user_id===user.id)setNotes(v=>v.some(x=>x.id===n.id)?v:[n,...v])}else if(p.eventType==='UPDATE'){const n=p.new as Note;setNotes(v=>v.map(x=>x.id===n.id?n:x))}else if(p.eventType==='DELETE'){const n=p.old as Note;setNotes(v=>v.filter(x=>x.id!==n.id))}}).subscribe();return()=>{void supabase.removeChannel(c)}},[user]);
  useEffect(()=>{if(!reminders.length)return;const timers:number[]=[];for(const r of reminders){if(r.completed_at||r.reminder_type!=='datetime'||!r.remind_at)continue;const delay=new Date(r.remind_at).getTime()-Date.now();if(delay>0&&delay<2147483647){timers.push(window.setTimeout(()=>{void fireReminder(r)},delay))}}return()=>timers.forEach(t=>clearTimeout(t))},[reminders]);
  useEffect(()=>{if(!reminders.some(r=>r.reminder_type==='location'&&!r.completed_at)||!navigator.geolocation)return;const watch=navigator.geolocation.watchPosition(async p=>{for(const r of reminders.filter(x=>x.reminder_type==='location'&&!x.completed_at&&x.location_lat!==null&&x.location_lng!==null)){const d=meters({lat:p.coords.latitude,lng:p.coords.longitude},{lat:r.location_lat!,lng:r.location_lng!});if(d<=Number(r.location_radius_m||250)){await fireReminder(r)}}});return()=>navigator.geolocation.clearWatch(watch)},[reminders]);

  async function load(){
    if(!user)return;setLoading(true);const [n,l,ll,r]=await Promise.all([supabase.from('notes').select('*').eq('user_id',user.id).order('is_pinned',{ascending:false}).order('sort_order'),supabase.from('note_labels').select('*').eq('user_id',user.id).order('name'),supabase.from('note_label_links').select('*'),supabase.from('note_reminders').select('*').eq('user_id',user.id).order('remind_at')]);
    if(n.error)setError(n.error.message);else setNotes((n.data??[]) as Note[]);if(l.data)setLabels(l.data as Label[]);if(ll.data){const m:Record<string,string[]>={};for(const x of ll.data as any[])(m[x.note_id]??=[]).push(x.label_id);setLinks(m)}if(r.data)setReminders(r.data as Reminder[]);setLoading(false);
    const invite=new URLSearchParams(location.search).get('invite');if(invite&&user.email){const {data}=await supabase.from('note_share_invites').select('*').eq('token',invite).maybeSingle();if(data&&data.email.toLowerCase()===user.email.toLowerCase()&&!data.accepted_at&&new Date(data.expires_at)>new Date()){await supabase.from('note_collaborators').upsert({note_id:data.note_id,user_id:user.id,invited_email:user.email,role:data.role,status:'accepted',accepted_at:new Date().toISOString()},{onConflict:'note_id,user_id'});await supabase.from('note_share_invites').update({accepted_at:new Date().toISOString()}).eq('id',data.id);history.replaceState({},'', '/notes');setSelectedId(data.note_id)}}
  }
  async function create(type:NoteType){if(!user)return;setNewMenu(false);const order=Math.max(-1,...notes.map(n=>Number(n.sort_order)||0))+1;const {data,e}=await supabase.from('notes').insert({user_id:user.id,title:'',content:'',note_type:type,sort_order:order}).select().single();if(e){setError(e.message);return}const n=data as Note;setNotes(v=>[n,...v]);setSelectedId(n.id)}
  function queue(patch:Partial<Note>){if(!selected)return;setNotes(v=>v.map(n=>n.id===selected.id?{...n,...patch}:n));if(saveRef.current)clearTimeout(saveRef.current);saveRef.current=window.setTimeout(async()=>{setSaving(true);const {error:e}=await supabase.from('notes').update(patch).eq('id',selected.id);if(e)setError(e.message);setSaving(false)},300)}
  async function update(patch:Partial<Note>){if(!selected)return;setSaving(true);setNotes(v=>v.map(n=>n.id===selected.id?{...n,...patch}:n));const {error:e}=await supabase.from('notes').update(patch).eq('id',selected.id);if(e)setError(e.message);setSaving(false)}
  async function remove(){if(!selected)return;await update({is_deleted:true,deleted_at:new Date().toISOString()});setSelectedId(null)}
  async function loadSelected(id:string){const [c,a]=await Promise.all([supabase.from('note_checklist_items').select('*').eq('note_id',id).order('position'),supabase.from('note_attachments').select('*').eq('note_id',id).order('created_at',{ascending:false})]);if(c.data)setCheck(v=>({...v,[id]:c.data as Checklist[]}));if(a.data){const arr=await Promise.all((a.data as Attachment[]).map(async x=>x.file_path?({...x,signed_url:(await supabase.storage.from('notes-media').createSignedUrl(x.file_path,3600)).data?.signedUrl}):x));setFiles(v=>({...v,[id]:arr}))}}
  async function addItem(parentId:string|null){if(!selected)return;const arr=check[selected.id]??[],pos=Math.max(-1,...arr.map(x=>x.position))+1,{data,e}=await supabase.from('note_checklist_items').insert({note_id:selected.id,parent_id:parentId,title:'',position:pos}).select().single();if(e){setError(e.message);return}setCheck(v=>({...v,[selected.id]:[...arr,data as Checklist]}))}
  async function saveItem(item:Checklist,patch:Partial<Checklist>){const arr=(check[selected!.id]??[]).map(x=>x.id===item.id?{...x,...patch}:x);if(patch.is_completed){arr.sort((a,b)=>Number(a.is_completed)-Number(b.is_completed)).forEach((x,i)=>x.position=i);await supabase.from('note_checklist_items').upsert(arr.map(x=>({id:x.id,note_id:selected!.id,parent_id:x.parent_id,title:x.title,is_completed:x.is_completed,position:x.position})))}else await supabase.from('note_checklist_items').update(patch).eq('id',item.id);setCheck(v=>({...v,[selected!.id]:arr))}
  async function addLabel(){if(!user||!newLabel.trim())return;const {data,e}=await supabase.from('note_labels').insert({user_id:user.id,name:newLabel.trim(),color:selected?.color??'default'}).select().single();if(e)setError(e.message);else{setLabels(v=>[...v,data as Label]);setNewLabel('')}}
  async function toggleLabel(id:string){if(!selected)return;const arr=links[selected.id]??[];if(arr.includes(id)){await supabase.from('note_label_links').delete().eq('note_id',selected.id).eq('label_id',id);setLinks(v=>({...v,[selected.id]:arr.filter(x=>x!==id)}))}else{await supabase.from('note_label_links').insert({note_id:selected.id,label_id:id});setLinks(v=>({...v,[selected.id]:[...arr,id]}))}}
  async function upload(file:File,type:'image'|'drawing'|'file'){if(!user||!selected)return;const path=user.id+'/'+selected.id+'/'+crypto.randomUUID()+'-'+file.name.replace(/[^a-z0-9._-]/gi,'');const {error:e}=await supabase.storage.from('notes-media').upload(path,file,{contentType:file.type,upsert:false});if(e){setError(e.message);return}await supabase.from('note_attachments').insert({note_id:selected.id,user_id:user.id,attachment_type:type,file_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size});await loadSelected(selected.id)}
  function img(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(f)void upload(f,'image');e.currentTarget.value=''}
  async function recordStart(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),r=new MediaRecorder(stream);mediaRef.current=r;chunks.current=[];setSeconds(0);setRecording(true);const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SR){const s=new SR();s.lang='pt-BR';s.continuous=true;s.interimResults=true;let t='';s.onresult=(ev:any)=>{for(let i=ev.resultIndex;i<ev.results.length;i++)if(ev.results[i].isFinal)t+=' '+ev.results[i][0].transcript;setNotes(v=>v.map(n=>n.id===selected?.id?{...n,transcript:t.trim()}:n))};s.start();speech.current={s,text:()=>t}}r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const b=new Blob(chunks.current,{type:r.mimeType||'audio/webm'}),f=new File([b],'audio-'+Date.now()+'.webm',{type:b.type});const path=user!.id+'/'+selected!.id+'/'+crypto.randomUUID()+'.webm';await supabase.storage.from('notes-media').upload(path,f,{contentType:f.type});const tr=speech.current?.text?.()||selected!.transcript||'';await supabase.from('note_attachments').insert({note_id:selected!.id,user_id:user!.id,attachment_type:'audio',file_path:path,file_name:f.name,mime_type:f.type,size_bytes:f.size,transcript:tr});await update({transcript:tr});await loadSelected(selected!.id);speech.current?.s?.stop?.();speech.current=null};r.start();timerRef.current=window.setInterval(()=>setSeconds(v=>v+1),1000)}catch(e){setError(e instanceof Error?e.message:'Microfone indisponível')}}
  function recordStop(){mediaRef.current?.stop();if(timerRef.current)clearInterval(timerRef.current);setRecording(false)}
  function drawDown(e:React.PointerEvent<HTMLCanvasElement>){const c=canvasRef.current;if(!c)return;c.setPointerCapture(e.pointerId);const x=c.getContext('2d')!,r=c.getBoundingClientRect();x.lineCap='round';x.lineJoin='round';x.lineWidth=drawTool==='marker'?14:4;x.globalAlpha=drawTool==='marker'?.25:1;x.strokeStyle=drawTool==='eraser'?'#fff':'#171717';x.beginPath();x.moveTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height)}
  function drawMove(e:React.PointerEvent<HTMLCanvasElement>){const c=canvasRef.current;if(!c||e.buttons!==1)return;const x=c.getContext('2d')!,r=c.getBoundingClientRect();x.lineTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height);x.stroke()}
  async function saveDraw(){if(!user||!selected||!canvasRef.current)return;const b=await new Promise<Blob|null>(r=>canvasRef.current!.toBlob(r,'image/png'));if(!b)return;const f=new File([b],'desenho-'+Date.now()+'.png',{type:'image/png'});await upload(f,'drawing')}
  async function extractOcr(a:Attachment){try{const Detector=(window as any).TextDetector;if(typeof Detector!=='function'){setError('OCR nativo não está disponível neste navegador.');return}if(!a.signed_url||!selected)return;const img=new Image();img.crossOrigin='anonymous';img.src=a.signed_url;await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject});const detector=new Detector();const blocks=await detector.detect(img);const text=blocks.map((b:any)=>b.rawValue||'').join(' ').trim();if(text){await update({ocr_text:(selected.ocr_text?selected.ocr_text+'\n':'')+text});setError('') }else setError('Nenhum texto foi detectado na imagem.')}catch{setError('Não foi possível executar o OCR neste navegador.')}}
  async function fireReminder(r:Reminder){if('Notification' in window&&Notification.permission!=='granted')await Notification.requestPermission();if('Notification' in window&&Notification.permission==='granted')new Notification('Notas',{body:r.title||'Você tem uma nota para lembrar.'});if(r.repeat_rule&&r.repeat_rule!=='none'&&r.remind_at){const d=new Date(r.remind_at);if(r.repeat_rule==='daily')d.setDate(d.getDate()+1);if(r.repeat_rule==='weekly')d.setDate(d.getDate()+7);if(r.repeat_rule==='monthly')d.setMonth(d.getMonth()+1);await supabase.from('note_reminders').update({remind_at:d.toISOString()}).eq('id',r.id);setReminders(v=>v.map(x=>x.id===r.id?{...x,remind_at:d.toISOString()}:x))}else{await supabase.from('note_reminders').update({completed_at:new Date().toISOString()}).eq('id',r.id);setReminders(v=>v.map(x=>x.id===r.id?{...x,completed_at:new Date().toISOString()}:x))}}
  async function addReminder(kind:'datetime'|'location'){if(!selected||!user)return;if(kind==='datetime'&&!remindAt)return;if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();let payload:any={note_id:selected.id,user_id:user.id,reminder_type:kind,title:selected.title||'Lembrete',repeat_rule:repeat==='none'?null:repeat};if(kind==='datetime')payload.remind_at=new Date(remindAt).toISOString();else await new Promise<void>(resolve=>navigator.geolocation.getCurrentPosition(async p=>{payload.location_lat=p.coords.latitude;payload.location_lng=p.coords.longitude;payload.location_radius_m=250;payload.location_trigger=locationTrigger;resolve()}));const {data,e}=await supabase.from('note_reminders').insert(payload).select().single();if(e)setError(e.message);else{setReminders(v=>[...v,data as Reminder]);setReminder(false);await update({reminder_at:kind==='datetime'?payload.remind_at:null})}}
  async function shareNote(){if(!selected)return;const t=(selected.title+'\n\n'+plain(selected.content)).trim();if(navigator.share){try{await navigator.share({title:selected.title||'Nota',text:t})}catch{}}else{await navigator.clipboard?.writeText(t);window.open('mailto:?subject='+encodeURIComponent(selected.title||'Nota')+'&body='+encodeURIComponent(t),'_blank')}}
  async function invite(e:FormEvent){e.preventDefault();if(!selected||!user||!shareEmail.trim())return;const token=crypto.randomUUID().replace(/-/g,'');const {data,e:err}=await supabase.from('note_share_invites').insert({note_id:selected.id,inviter_id:user.id,email:shareEmail.trim().toLowerCase(),role:'editor',token}).select().single();if(err){setError(err.message);return}const url=location.origin+'/notes?invite='+data.token;window.open('mailto:'+encodeURIComponent(shareEmail)+'?subject='+encodeURIComponent('Convite para uma nota')+'&body='+encodeURIComponent('Abra e aceite este convite: '+url),'_blank');setShareEmail('')}
  function exportOne(f:'json'|'md'|'txt'){if(!selected)return;const p=plain(selected.content),n=selected.title||'nota';if(f==='json')download(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'}),n+'.json');if(f==='md')download(new Blob(['# '+n+'\n\n'+p],{type:'text/markdown'}),n+'.md');if(f==='txt')download(new Blob([p],{type:'text/plain'}),n+'.txt')}
  function exportAll(){download(new Blob([JSON.stringify(notes,null,2)],{type:'application/json'}),'notas-export.json')}
  async function copyDocs(){if(!selected)return;await navigator.clipboard?.writeText((selected.title+'\n\n'+plain(selected.content)).trim());window.open('https://docs.google.com/document/create','_blank')}
  async function downloadFile(a:Attachment){if(!a.signed_url)return;download(await (await fetch(a.signed_url)).blob(),a.file_name||'arquivo')}
  const visible=useMemo(()=>notes.filter(n=>{if(filter==='trash')return n.is_deleted;if(n.is_deleted)return false;if(filter==='pinned')return n.is_pinned;if(filter==='archive')return n.is_archived;return !n.is_archived}).filter(n=>typeFilter==='all'||n.note_type===typeFilter).filter(n=>colorFilter==='all'||n.color===colorFilter).filter(n=>labelFilter==='all'||(links[n.id]??[]).includes(labelFilter)).filter(n=>reminderFilter==='all'||(reminderFilter==='with'?reminders.some(r=>r.note_id===n.id&&!r.completed_at):!reminders.some(r=>r.note_id===n.id&&!r.completed_at))).filter(n=>!query||(n.title+' '+plain(n.content)+' '+n.ocr_text+' '+n.transcript).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.is_pinned===b.is_pinned?(a.sort_order-b.sort_order):a.is_pinned?-1:1),[notes,filter,typeFilter,colorFilter,labelFilter,reminderFilter,links,reminders,query]);

  return <div className={cn('notes-shell',dark&&'is-dark')}>
    <aside className="notes-sidebar"><div className="notes-brand"><div><strong>Notas</strong><span>Espaço pessoal</span></div></div>
      <div className="notes-new-wrap"><button className="notes-new" onClick={()=>void create('text')}><Plus size={17}/> Nova nota <kbd>⌘N</kbd></button><button className="notes-new-menu" onClick={()=>setNewMenu(v=>!v)}><ChevronDown size={15}/></button>{newMenu&&<div className="notes-popover new-menu">{types.map(t=><button key={t.key} onClick={()=>void create(t.key)}><t.icon size={15}/>{t.label}</button>)}</div>}</div>
      <nav className="notes-nav">{[{k:'all',l:'Todas',icon:Grid2X2},{k:'pinned',l:'Fixadas',icon:Pin},{k:'archive',l:'Arquivo',icon:Archive},{k:'trash',l:'Lixeira',icon:Trash2}].map(item=>{const Icon=item.icon;return <button key={item.k} className={cn('notes-nav-item',filter===item.k&&'active')} onClick={()=>{setFilter(item.k);setSelectedId(null)}}><Icon size={16}/><span>{item.l}</span></button>})}</nav>
      <div className="notes-sidebar-extra"><button onClick={()=>setFilters(v=>!v)}><Filter size={14}/> Filtros</button><button onClick={exportAll}><Download size={14}/> Exportar tudo</button></div>
      <div className="notes-sidebar-foot"><span>{notes.filter(n=>!n.is_deleted).length} notas</span><span className="notes-status-dot"/>Sincronizado</div>
    </aside>
    <main className="notes-main"><header className="notes-toolbar"><button className="notes-menu-button" onClick={()=>document.querySelector('.notes-sidebar')?.classList.toggle('mobile-open')}><Menu size={18}/></button><div className="notes-search"><Search size={17}/><input id="notes-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar notas..." /><kbd><Command size={11}/>K</kbd></div><div className="notes-toolbar-actions"><button className={cn('notes-icon-button',view==='grid'&&'active')} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button><button className={cn('notes-icon-button',view==='list'&&'active')} onClick={()=>setView('list')}><List size={17}/></button><button className="notes-primary" onClick={()=>void create('text')}><Plus size={16}/><span>Nova</span></button><button className="notes-icon-button" onClick={()=>setTheme(theme==='system'?'dark':theme==='dark'?'light':'system')}>{dark?'☾':'☀'}</button></div></header>
      {filters&&<div className="notes-filter-bar"><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value as any)}><option value="all">Todos os tipos</option>{types.map(t=><option value={t.key} key={t.key}>{t.label}</option>)}</select><select value={colorFilter} onChange={e=>setColorFilter(e.target.value as any)}><option value="all">Todas as cores</option>{colorOptions.map(c=><option value={c.key} key={c.key}>{c.label}</option>)}</select><select value={labelFilter} onChange={e=>setLabelFilter(e.target.value)}><option value="all">Todos os marcadores</option>{labels.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select><select value={reminderFilter} onChange={e=>setReminderFilter(e.target.value)}><option value="all">Qualquer lembrete</option><option value="with">Com lembrete</option><option value="without">Sem lembrete</option></select></div>}
      <section className={cn('notes-content',view==='list'&&'list-view')}><div className="notes-heading"><div><p className="eyebrow">Seu espaço</p><h1>{filter==='trash'?'Lixeira':filter==='pinned'?'Fixadas':filter==='archive'?'Arquivo':'Todas as notas'}</h1></div><span>{visible.length}</span></div>{error&&<div className="notes-alert">{error}<button onClick={()=>setError('')}><X size={14}/></button></div>}{loading?<div className="notes-empty"><Loader2 className="spin" size={22}/><p>Carregando…</p></div>:visible.length===0?<div className="notes-empty"><div className="empty-orb"><Plus size={20}/></div><h2>Comece com uma nota</h2><p>Texto, checklist, foto, desenho ou voz.</p>{filter!=='trash'&&<button className="notes-primary" onClick={()=>void create('text')}><Plus size={16}/> Criar nota</button>}</div>:<div className="notes-grid">{visible.map(n=><article key={n.id} draggable={filter==='all'} onDragStart={e=>e.dataTransfer.setData('text/plain',n.id)} onDragOver={e=>e.preventDefault()} onDrop={async e=>{const d=e.dataTransfer.getData('text/plain');if(!d||d===n.id)return;const arr=[...notes].sort((a,b)=>a.sort_order-b.sort_order),from=arr.findIndex(x=>x.id===d),to=arr.findIndex(x=>x.id===n.id);if(from<0||to<0)return;const[m]=arr.splice(from,1);arr.splice(to,0,m);arr.forEach((x,i)=>x.sort_order=i);setNotes(arr);await Promise.all(arr.map(x=>supabase.from('notes').update({sort_order:x.sort_order}).eq('id',x.id)))}} className={cn('note-card','note-color-'+n.color)} onClick={()=>setSelectedId(n.id)}><div className="note-card-top">{n.is_pinned&&<Pin size={13}/>}<span>{new Date(n.updated_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'})}</span></div><div className="note-type-badge">{types.find(t=>t.key===n.note_type)?.label}</div><h3>{n.title||'Sem título'}</h3><p>{plain(n.content)||n.ocr_text||n.transcript||'Comece a escrever…'}</p>{(links[n.id]??[]).length>0&&<div className="note-labels">{(links[n.id]??[]).map(id=>labels.find(l=>l.id===id)).filter(Boolean).slice(0,3).map(l=><span key={l!.id}>{l!.name}</span>)}</div>}</article>)}</div>}</section></main>
    {selected&&<div className="notes-editor-overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setSelectedId(null)}}><section className={cn('notes-editor','note-color-'+selected.color)}>
      <header className="notes-editor-header"><button className="notes-icon-button" onClick={()=>setSelectedId(null)}><ChevronLeft size={18}/></button><div className="editor-actions"><span>{saving?'Salvando…':'Salvo'}</span><button className={cn('notes-icon-button',selected.is_pinned&&'active')} onClick={()=>void update({is_pinned:!selected.is_pinned})}><Pin size={17}/></button><button className="notes-icon-button" onClick={()=>void update({is_archived:true})}><Archive size={17}/></button><button className="notes-icon-button" onClick={()=>setReminder(v=>!v)}><Clock3 size={17}/></button><button className="notes-icon-button" onClick={()=>setShare(v=>!v)}><Share2 size={17}/></button><button className="notes-icon-button" onClick={()=>setLabelPanel(v=>!v)}><Tag size={17}/></button><button className="notes-icon-button" onClick={()=>setMore(v=>!v)}><MoreHorizontal size={17}/></button><button className="notes-icon-button danger" onClick={()=>void remove()}><Trash2 size={17}/></button></div></header>
      <div className="editor-type-tabs">{types.map(t=><button key={t.key} className={selected.note_type===t.key?'active':''} onClick={()=>void update({note_type:t.key})}><t.icon size={14}/>{t.label}</button>)}</div>
      {more&&<div className="notes-popover editor-menu"><button onClick={()=>window.print()}><Printer size={15}/> Imprimir</button><button onClick={()=>void shareNote()}><Send size={15}/> Enviar / compartilhar</button><button onClick={()=>void copyDocs()}><FileText size={15}/> Copiar para Google Docs</button><button onClick={()=>exportOne('md')}><FileDown size={15}/> Markdown</button><button onClick={()=>exportOne('txt')}><Download size={15}/> Texto</button><button onClick={()=>exportOne('json')}><FileDown size={15}/> JSON</button></div>}
      {share&&<div className="notes-popover share-panel"><h3>Compartilhar</h3><p>Envie um convite por e-mail. A edição conjunta sincroniza pelo banco em tempo real.</p><form onSubmit={invite}><input type="email" required value={shareEmail} onChange={e=>setShareEmail(e.target.value)} placeholder="email@exemplo.com"/><button className="notes-primary"><Mail size={14}/> Criar convite</button></form></div>}
      {reminder&&<div className="notes-popover reminder-panel"><label>Data e hora<input type="datetime-local" value={remindAt} onChange={e=>setRemindAt(e.target.value)}/></label><label>Repetição<select value={repeat} onChange={e=>setRepeat(e.target.value)}><option value="none">Não repetir</option><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></select></label><button onClick={()=>void addReminder('datetime')}>Salvar lembrete</button><div className="location-choice"><button className={locationTrigger==='arrive'?'active':''} onClick={()=>setLocationTrigger('arrive')}>Ao chegar</button><button className={locationTrigger==='leave'?'active':''} onClick={()=>setLocationTrigger('leave')}>Ao sair</button></div><button onClick={()=>void addReminder('location')}><MapPin size={14}/> Lembrete por localização</button></div>}
      {labelPanel&&<div className="notes-popover labels-panel"><div className="label-chips">{labels.map(l=><button key={l.id} className={(links[selected.id]??[]).includes(l.id)?'active':''} onClick={()=>void toggleLabel(l.id)}>{l.name}</button>)}</div><div className="label-create"><input value={newLabel} onChange={e=>setNewLabel(e.target.value)} placeholder="Novo marcador"/><button onClick={()=>void addLabel()}><Plus size={14}/></button></div></div>}
      <input className="notes-title-input" value={selected.title} onChange={e=>queue({title:e.target.value})} placeholder="Título"/>
      {selected.note_type==='text'&&<><div className="editor-formatbar"><button onClick={()=>document.execCommand('bold')}><Bold size={15}/></button><button onClick={()=>document.execCommand('italic')}><Italic size={15}/></button><button onClick={()=>document.execCommand('underline')}><Underline size={15}/></button><button onClick={()=>{const u=prompt('URL do link');if(u)document.execCommand('createLink',false,u)}}><Link2 size={15}/></button></div><div className="notes-body-editor" key={selected.id} ref={e=>{editorRef.current=e;if(e&&!e.dataset.ready){e.innerHTML=selected.content||'';e.dataset.ready='1'}}} contentEditable suppressContentEditableWarning onInput={e=>queue({content:e.currentTarget.innerHTML})} data-placeholder="Escreva o que estiver pensando…"/></>}
      {selected.note_type==='checklist'&&<div className="checklist-editor">{(check[selected.id]??[]).sort((a,b)=>a.position-b.position).map(i=><div className={cn('check-row',i.parent_id&&'subitem')} key={i.id}><button className={cn('check-box',i.is_completed&&'done')} onClick={()=>void saveItem(i,{is_completed:!i.is_completed})}>{i.is_completed&&<Check size={13}/>}</button><input value={i.title} onChange={e=>setCheck(v=>({...v,[selected.id]:(v[selected.id]??[]).map(x=>x.id===i.id?{...x,title:e.target.value}:x)}))} onBlur={e=>void saveItem(i,{title:e.target.value})} placeholder="Item"/><button onClick={()=>void addItem(i.id)}><Plus size={14}/></button></div>)}<button className="add-check" onClick={()=>void addItem(null)}><Plus size={15}/> Adicionar item</button></div>}
      {selected.note_type==='image'&&<div className="media-note"><label className="notes-primary"><ImagePlus size={15}/> Foto / câmera<input hidden type="file" accept="image/*" capture="environment" onChange={img}/></label>{(files[selected.id]??[]).filter(x=>x.attachment_type==='image').map(a=><div className="attachment-card" key={a.id}>{a.signed_url&&<img src={a.signed_url} alt={a.file_name}/>}<button onClick={()=>void extractOcr(a)}>Extrair texto</button><button onClick={()=>void downloadFile(a)}><Download size={14}/> Baixar</button></div>)}</div>}
      {selected.note_type==='audio'&&<div className="audio-editor"><button className={cn('record-button',recording&&'stop')} onClick={()=>recording?recordStop():void recordStart()}>{recording?<Square size={17}/>:<Mic size={20}/>}</button><strong>{recording?'Gravando…':'Gravar áudio'}</strong><span>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</span><p>{selected.transcript||'A transcrição aparece aqui quando o navegador oferecer reconhecimento de voz.'}</p>{(files[selected.id]??[]).filter(x=>x.attachment_type==='audio').map(a=><audio key={a.id} controls src={a.signed_url}/>)}</div>}
      {selected.note_type==='drawing'&&<div className="drawing-editor"><div className="drawing-toolbar"><button className={drawTool==='pen'?'active':''} onClick={()=>setDrawTool('pen')}>Caneta</button><button className={drawTool==='marker'?'active':''} onClick={()=>setDrawTool('marker')}>Marcador</button><button className={drawTool==='eraser'?'active':''} onClick={()=>setDrawTool('eraser')}><Eraser size={14}/> Borracha</button><button onClick={()=>void saveDraw()}><Check size={14}/> Salvar</button></div><canvas ref={canvasRef} width={1200} height={650} onPointerDown={drawDown} onPointerMove={drawMove} className="drawing-canvas"/></div>}
      <footer className="notes-editor-footer"><div className="color-picker">{colorOptions.map(c=><button key={c.key} title={c.label} className={cn('color-dot',selected.color===c.key&&'selected')} style={{background:c.hex}} onClick={()=>void update({color:c.key})}/>)}</div><div className="editor-footer-right"><label className="attach-button"><Upload size={14}/><input hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,'file')}}/></label><span>{plain(selected.content).split(/\s+/).filter(Boolean).length} palavras</span></div></footer>
    </section></div>}
  </div>
}