import { useState, useEffect } from 'react';
import { Sparkles, Loader2, Package, ShieldCheck, Timer, Video, Quote } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import type { SalesPage, SalesBlock } from '@/types';

const FONT_SIZES: Record<string,string>={xs:'text-xs',sm:'text-sm',base:'text-base',lg:'text-lg',xl:'text-xl','2xl':'text-2xl','3xl':'text-3xl','4xl':'text-4xl','5xl':'text-5xl','6xl':'text-6xl','7xl':'text-7xl'};
interface Settings{fontSize?:string;fontFamily?:string;align?:string;color?:string;bgColor?:string;fontWeight?:string;paddingY?:number;buttonUrl?:string;buttonBg?:string;buttonColor?:string;buttonRadius?:number;spacerHeight?:number;imageRounded?:boolean;imageWidth?:number;subheading?:string;buttonText?:string;imageUrl?:string;videoUrl?:string;columns?:number;items?:Array<Record<string,string|number|boolean>>;price?:string;compareAt?:string;badge?:string;features?:string;author?:string;role?:string;days?:string;text?:string;endAt?:string;title?:string;subtitle?:string;}
interface PageSettings{backgroundColor?:string;backgroundImage?:string;backgroundSize?:'cover'|'contain'|'auto';backgroundPosition?:string;backgroundRepeat?:'no-repeat'|'repeat'|'repeat-x'|'repeat-y';overlayColor?:string;overlayOpacity?:number;contentWidth?:'narrow'|'medium'|'wide';}

function toEmbedUrl(url:string){try{const u=new URL(url);if(u.hostname.includes('youtube.com')){if(u.pathname.includes('/embed/'))return url;const v=u.searchParams.get('v');if(v)return 'https://www.youtube.com/embed/'+v;const parts=u.pathname.split('/').filter(Boolean);const idx=parts.indexOf('shorts');if(idx>=0&&parts[idx+1])return 'https://www.youtube.com/embed/'+parts[idx+1];}if(u.hostname.includes('youtu.be'))return 'https://www.youtube.com/embed/'+u.pathname.slice(1);return url}catch{return url}}
const widthClass=(settings:PageSettings)=>settings.contentWidth==='narrow'?'max-w-3xl':settings.contentWidth==='wide'?'max-w-6xl':'max-w-5xl';

function Button({text,url,settings}:{text:string;url:string;settings:Settings}){return <a href={url||'#'} target="_blank" rel="noopener noreferrer" className="inline-block px-7 py-3 font-semibold transition hover:opacity-90" style={{fontFamily:settings.fontFamily||'Inter',borderRadius:settings.buttonRadius??12,backgroundColor:settings.buttonBg||'#0f172a',color:settings.buttonColor||'#fff'}}>{text||'Clique aqui'}</a>}

function CountdownBlock({label,endAt}:{label:string;endAt:string}){
  const getRemaining=()=>{const target=new Date(endAt.replace(' ','T')).getTime();const diff=Math.max(0,target-Date.now());return {diff,days:Math.floor(diff/86400000),hours:Math.floor(diff/3600000)%24,minutes:Math.floor(diff/60000)%60,seconds:Math.floor(diff/1000)%60};};
  const [remaining,setRemaining]=useState(getRemaining);
  useEffect(()=>{const timer=window.setInterval(()=>setRemaining(getRemaining()),1000);return()=>window.clearInterval(timer)},[endAt]);
  if(!endAt)return <section className="px-6 text-center py-5"><div className="rounded-2xl bg-slate-950 text-white p-5 max-w-2xl mx-auto"><Timer className="w-5 h-5 mx-auto opacity-70"/><p className="font-bold mt-2">{label}</p><p className="text-xs text-white/50 mt-2">Defina a data final no editor.</p></div></section>;
  if(remaining.diff<=0)return <section className="px-6 text-center py-5"><div className="rounded-2xl bg-slate-950 text-white p-5 max-w-2xl mx-auto"><Timer className="w-5 h-5 mx-auto opacity-70"/><p className="font-bold mt-2">Oferta encerrada</p></div></section>;
  const cell=(value:number,label:string)=><div className="rounded-xl bg-white/10 px-3 py-2 min-w-16"><p className="text-2xl font-black tabular-nums">{String(value).padStart(2,'0')}</p><p className="text-[10px] uppercase tracking-wider text-white/45">{label}</p></div>;
  return <section className="px-6 text-center py-5"><div className="rounded-2xl bg-slate-950 text-white p-5 max-w-2xl mx-auto"><Timer className="w-5 h-5 mx-auto opacity-70"/><p className="font-bold mt-2">{label}</p><div className="flex items-center justify-center gap-2 mt-4">{remaining.days>0&&cell(remaining.days,'dias')}{cell(remaining.hours,'horas')}{cell(remaining.minutes,'min')}{cell(remaining.seconds,'seg')}</div></div></section>;
}
function Blocks({blocks}:{blocks:SalesBlock[]}){
  return <div>{blocks.map(block=>{const s=block.settings as Settings;const align=s.align||'left';const wrap=align==='center'?'text-center':align==='right'?'text-right':'text-left';const font=FONT_SIZES[s.fontSize||'base']||'text-base';const base={fontFamily:s.fontFamily||'Inter',backgroundColor:s.bgColor||'transparent',paddingTop:s.paddingY??10,paddingBottom:s.paddingY??10};
  if(block.block_type==='hero')return <section key={block.id} className={'px-6 '+wrap} style={{...base,paddingTop:s.paddingY??32,paddingBottom:s.paddingY??32}}><p className="text-xs uppercase tracking-[0.2em] opacity-60 mb-3">{s.title||'Oferta'}</p><h1 className={(font==='text-base'?'text-5xl':font)+' font-black leading-tight'} style={{color:s.color||'#0f172a'}}>{block.content}</h1>{s.subheading&&<p className="max-w-2xl mx-auto mt-4 text-lg leading-7 opacity-75">{s.subheading}</p>}<div className="mt-6"><Button text={s.buttonText||'Quero começar'} url={s.buttonUrl||'#'} settings={s}/></div>{s.imageUrl&&<img src={s.imageUrl} alt="" className="max-w-full max-h-80 object-contain mx-auto mt-8 rounded-2xl"/>}</section>;
  if(block.block_type==='heading'||block.block_type==='text')return <div key={block.id} className={'px-6 '+wrap} style={base}><p className={font+' leading-relaxed '+(s.fontWeight==='bold'?'font-bold':'')+' whitespace-pre-wrap'} style={{color:s.color||'#334155'}}>{block.content}</p></div>;
  if(block.block_type==='image')return block.content?<div key={block.id} className="px-6 flex justify-center" style={{paddingTop:s.paddingY??12,paddingBottom:s.paddingY??12,backgroundColor:s.bgColor||'transparent'}}><img src={block.content} alt="" style={{width:`${Math.min(100,Math.max(20,s.imageWidth||100))}%`}} className={'max-w-full object-contain '+(s.imageRounded===false?'':'rounded-xl')}/></div>:null;
  if(block.block_type==='button')return <div key={block.id} className={'px-6 flex '+(align==='center'?'justify-center':align==='right'?'justify-end':'justify-start')} style={{backgroundColor:s.bgColor||'transparent',paddingTop:s.paddingY??12,paddingBottom:s.paddingY??12}}><Button text={block.content} url={s.buttonUrl||'#'} settings={s}/></div>;
  if(block.block_type==='video')return <section key={block.id} className="px-6 text-center" style={{paddingTop:s.paddingY??18,paddingBottom:s.paddingY??18,backgroundColor:s.bgColor||'transparent'}}>{s.title&&<h3 className="text-xl font-bold mb-4">{s.title}</h3>}{s.videoUrl?<div className="aspect-video rounded-2xl overflow-hidden bg-black max-w-3xl mx-auto"><iframe title={block.content||'Vídeo'} src={toEmbedUrl(s.videoUrl)} className="w-full h-full" loading="lazy" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/></div>:<div className="aspect-video rounded-2xl bg-slate-100 flex items-center justify-center text-slate-400 max-w-3xl mx-auto"><Video className="w-7 h-7"/><span className="ml-2 text-sm">{block.content||'Adicione a URL do vídeo'}</span></div>}</section>;
  if(block.block_type==='features'||block.block_type==='benefits')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??20,paddingBottom:s.paddingY??20,backgroundColor:s.bgColor||'transparent'}}><h2 className="text-2xl sm:text-3xl font-black text-center mb-6">{block.content}</h2><div className={'grid gap-4 '+(s.columns===2?'md:grid-cols-2':s.columns===4?'md:grid-cols-2 lg:grid-cols-4':'md:grid-cols-3')}>{(s.items||[]).map((item,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white/85 p-5"><div className="w-9 h-9 rounded-xl bg-slate-900 text-white flex items-center justify-center text-xs font-bold mb-4">{i+1}</div><h3 className="font-bold text-slate-900">{String(item.title||'Benefício')}</h3><p className="text-sm text-slate-600 mt-2 leading-6">{String(item.text||'')}</p></div>)}</div></section>;
  if(block.block_type==='testimonial')return <section key={block.id} className="px-6 text-center" style={{paddingTop:s.paddingY??20,paddingBottom:s.paddingY??20,backgroundColor:s.bgColor||'transparent'}}><div className="max-w-3xl mx-auto rounded-2xl border border-slate-200 bg-white/90 p-7"><Quote className="w-6 h-6 mx-auto mb-3 text-slate-400"/><p className="text-lg leading-8 font-medium">{block.content}</p><p className="text-sm font-bold mt-5">{s.author||'Cliente'}</p><p className="text-xs text-slate-400">{s.role||''}</p></div></section>;
  if(block.block_type==='testimonials')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??20,paddingBottom:s.paddingY??20}}><h2 className="text-2xl sm:text-3xl font-black text-center mb-6">{block.content}</h2><div className="grid gap-4 md:grid-cols-2">{(s.items||[]).map((item,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white/90 p-6"><Quote className="w-5 h-5 text-slate-400 mb-3"/><p className="text-sm leading-7">{String(item.quote||'')}</p><p className="text-xs font-bold mt-4">{String(item.author||'Cliente')}</p><p className="text-[11px] text-slate-400">{String(item.role||'')}</p></div>)}</div></section>;
  if(block.block_type==='logos')return <section key={block.id} className="px-6 text-center" style={{paddingTop:s.paddingY??18,paddingBottom:s.paddingY??18}}><h3 className="text-xs uppercase tracking-[0.18em] text-slate-400 mb-4">{block.content}</h3><div className="flex flex-wrap gap-3 justify-center">{(s.items||[]).map((item,i)=><span key={i} className="px-4 py-2 rounded-full border border-slate-200 bg-white/80 text-sm font-semibold text-slate-500">{String(item.name||'Marca')}</span>)}</div></section>;
  if(block.block_type==='stats')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??18,paddingBottom:s.paddingY??18}}><h2 className="text-2xl font-black text-center mb-5">{block.content}</h2><div className={'grid gap-3 '+(s.columns===2?'md:grid-cols-2':s.columns===4?'md:grid-cols-4':'md:grid-cols-3')}>{(s.items||[]).map((item,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white/80 p-5 text-center"><p className="text-2xl font-black">{String(item.value||'')}</p><p className="text-xs text-slate-500 mt-1">{String(item.label||'')}</p></div>)}</div></section>;
  if(block.block_type==='product')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??24,paddingBottom:s.paddingY??24}}><div className="grid md:grid-cols-2 gap-6 items-center rounded-3xl border border-slate-200 bg-white/90 p-6">{s.imageUrl?<img src={s.imageUrl} alt="" className="w-full max-h-80 object-contain rounded-2xl"/>:<div className="aspect-square rounded-2xl bg-slate-100 flex items-center justify-center text-slate-400"><Package/></div>}<div><h2 className="text-3xl font-black">{block.content}</h2>{s.price&&<p className="text-3xl font-black mt-4">{s.price}</p>}<ul className="mt-4 space-y-2 text-sm text-slate-600">{String(s.features||'').split('\n').filter(Boolean).map((x,i)=><li key={i} className="flex gap-2"><span className="text-emerald-600">✓</span>{x}</li>)}</ul><div className="mt-6"><Button text={s.buttonText||'Quero comprar'} url={s.buttonUrl||'#'} settings={s}/></div></div></div></section>;
  if(block.block_type==='pricing')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??26,paddingBottom:s.paddingY??26}}><div className="max-w-md mx-auto rounded-3xl border-2 border-slate-900 bg-white p-7 text-center relative overflow-hidden">{s.badge&&<div className="inline-flex px-3 py-1 rounded-full bg-slate-900 text-white text-[11px] font-bold uppercase tracking-wider">{s.badge}</div>}<h2 className="text-2xl font-black mt-3">{block.content}</h2>{s.compareAt&&<p className="text-sm text-slate-400 line-through mt-3">{s.compareAt}</p>}<p className="text-5xl font-black mt-1">{s.price||'R$ 0'}</p><ul className="mt-5 text-sm text-left space-y-2">{String(s.features||'').split('\n').filter(Boolean).map((x,i)=><li key={i} className="flex gap-2"><span className="text-emerald-600">✓</span>{x}</li>)}</ul><div className="mt-6"><Button text={s.buttonText||'Quero começar'} url={s.buttonUrl||'#'} settings={s}/></div></div></section>;
  if(block.block_type==='comparison')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??24,paddingBottom:s.paddingY??24}}><h2 className="text-2xl font-black text-center mb-5">{block.content}</h2><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white/90"><table className="w-full text-sm"><thead><tr className="bg-slate-50"><th className="text-left p-3">Item</th><th className="p-3">Opção A</th><th className="p-3">Opção B</th></tr></thead><tbody>{(s.items||[]).map((item,i)=><tr key={i} className="border-t border-slate-100"><td className="p-3 font-medium">{String(item.feature||'')}</td><td className="p-3 text-center">{String(item.optionA||'')}</td><td className="p-3 text-center">{String(item.optionB||'')}</td></tr>)}</tbody></table></div></section>;
  if(block.block_type==='guarantee')return <section key={block.id} className="px-6 text-center" style={{paddingTop:s.paddingY??22,paddingBottom:s.paddingY??22}}><div className="max-w-2xl mx-auto rounded-3xl border border-emerald-200 bg-emerald-50 p-7"><ShieldCheck className="w-8 h-8 mx-auto text-emerald-600"/><h2 className="text-2xl font-black mt-3">{block.content}</h2><p className="text-sm text-emerald-900/70 leading-6 mt-3">{s.text||''}</p></div></section>;
  if(block.block_type==='faq')return <section key={block.id} className="px-6" style={{paddingTop:s.paddingY??22,paddingBottom:s.paddingY??22}}><h2 className="text-2xl font-black text-center mb-5">{block.content}</h2><div className="max-w-3xl mx-auto space-y-2">{(s.items||[]).map((item,i)=><details key={i} className="rounded-xl border border-slate-200 bg-white/90 p-4"><summary className="cursor-pointer font-semibold text-sm">{String(item.question||'Pergunta')}</summary><p className="text-sm text-slate-600 mt-3 leading-6">{String(item.answer||'')}</p></details>)}</div></section>;
  if(block.block_type==='countdown')return <div key={block.id}><CountdownBlock label={block.content} endAt={s.endAt||''}/></div>;
  if(block.block_type==='notice')return <div key={block.id} className={'px-6 '+wrap} style={{...base,fontWeight:'bold'}}><div className="rounded-xl px-4 py-3">{block.content}</div></div>;
  if(block.block_type==='cta')return <section key={block.id} className={'px-6 '+wrap} style={{...base,paddingTop:s.paddingY??28,paddingBottom:s.paddingY??28}}><div className="rounded-3xl bg-slate-950 text-white p-8"><h2 className="text-3xl font-black">{block.content}</h2>{s.subtitle&&<p className="text-white/60 mt-2">{s.subtitle}</p>}<div className="mt-5"><Button text={s.buttonText||'Quero começar'} url={s.buttonUrl||'#'} settings={s}/></div></div></section>;
  if(block.block_type==='spacer')return <div key={block.id} style={{height:s.spacerHeight||48,backgroundColor:s.bgColor||'transparent'}}/>;
  return <hr key={block.id} className="border-t" style={{marginTop:s.paddingY||12,marginBottom:s.paddingY||12,borderColor:s.color||'#e2e8f0'}}/>;
  })}</div>
}

export function PublicSalesPage({slug}:{slug:string}){
  const [blocks,setBlocks]=useState<SalesBlock[]>([]);
  const [page,setPage]=useState<SalesPage|null>(null);
  const [loading,setLoading]=useState(true);
  const [notFound,setNotFound]=useState(false);
  useEffect(()=>{let alive=true;supabase.from('sales_pages').select('*').eq('slug',slug.toLowerCase()).maybeSingle().then(async({data})=>{
    if(!alive)return;
    if(!data||!(data as SalesPage).is_published){setNotFound(true);setLoading(false);return;}
    const p=data as SalesPage;setPage(p);document.title=p.seo_title||p.title;
    const title=p.seo_title||p.title;const description=p.seo_description||p.title;
    let meta=document.querySelector('meta[name="description"]') as HTMLMetaElement|null;
    if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}meta.content=description;
    let robots=document.querySelector('meta[name="robots"]') as HTMLMetaElement|null;
    if(!robots){robots=document.createElement('meta');robots.name='robots';document.head.appendChild(robots)}robots.content='index,follow';
    const setOg=(property:string,value:string)=>{let el=document.querySelector('meta[property="'+property+'"]') as HTMLMetaElement|null;if(!el){el=document.createElement('meta');el.setAttribute('property',property);document.head.appendChild(el)}el.content=value};
    setOg('og:title',title);setOg('og:description',description);setOg('og:url',window.location.origin+'/p/'+encodeURIComponent(p.slug));
    const canonical=window.location.origin+'/p/'+encodeURIComponent(p.slug);
    let canonicalTag=document.querySelector('link[data-risegoat-canonical]') as HTMLLinkElement|null;
    if(!canonicalTag){canonicalTag=document.createElement('link');canonicalTag.rel='canonical';canonicalTag.setAttribute('data-risegoat-canonical','true');document.head.appendChild(canonicalTag)}canonicalTag.href=canonical;
    document.getElementById('risegoat-sales-schema')?.remove();
    const schema=document.createElement('script');schema.id='risegoat-sales-schema';schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:title,description,url:canonical});document.head.appendChild(schema);
    const {data:b}=await supabase.from('sales_blocks').select('*').eq('page_id',p.id).order('sort_order');
    if(alive){setBlocks((b as SalesBlock[])||[]);setLoading(false)}
  });return()=>{alive=false}},[slug]);
  if(loading)return <div className="min-h-screen flex items-center justify-center bg-slate-100"><Loader2 className="w-8 h-8 text-slate-300 animate-spin"/></div>;
  if(notFound||!page)return <div className="min-h-screen flex flex-col items-center justify-center bg-slate-950 text-center px-4"><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center mb-4"><Sparkles className="w-6 h-6 text-white"/></div><h1 className="text-xl font-bold text-white mb-2">Página não encontrada</h1><p className="text-sm text-slate-400">Esta página de venda não existe ou não está publicada.</p></div>;
  const ps:PageSettings={backgroundColor:'#ffffff',backgroundImage:'',backgroundSize:'cover',backgroundPosition:'center',backgroundRepeat:'no-repeat',overlayColor:'#000000',overlayOpacity:0,contentWidth:'medium',...(page.settings as PageSettings||{})};
  const background:React.CSSProperties={backgroundColor:ps.backgroundColor,backgroundImage:ps.backgroundImage?`url(${ps.backgroundImage})`:'none',backgroundSize:ps.backgroundSize,backgroundPosition:ps.backgroundPosition,backgroundRepeat:ps.backgroundRepeat};
  return <div className="min-h-screen relative" style={background}>
    {ps.overlayOpacity!>0&&<div className="absolute inset-0 pointer-events-none" style={{backgroundColor:ps.overlayColor,opacity:ps.overlayOpacity}}/>}
    <main className={'relative '+widthClass(ps)+' mx-auto px-4 sm:px-6 py-6 sm:py-10'}>{blocks.length===0?<p className="text-center text-slate-400 py-20">Esta página está vazia.</p>:<Blocks blocks={blocks}/>}</main>
    <div className="relative text-center pb-8"><a href="#/auth" className="inline-flex items-center gap-1.5 text-xs text-slate-300 hover:text-slate-400 transition"><Sparkles className="w-3 h-3"/>Powered by risegoat</a></div>
  </div>;
}
