/*
  RiseGoat email connections + newsletter campaigns.
  SMTP passwords are stored as AES-256-GCM ciphertext generated by Edge Functions.
*/
CREATE TABLE IF NOT EXISTS email_connections (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  smtp_host text NOT NULL, smtp_port integer NOT NULL, smtp_user text NOT NULL,
  smtp_password text NOT NULL, from_name text NOT NULL DEFAULT '', from_email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE email_connections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "owner_select_email_connection" ON email_connections;
CREATE POLICY "owner_select_email_connection" ON email_connections FOR SELECT TO authenticated USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "owner_delete_email_connection" ON email_connections;
CREATE POLICY "owner_delete_email_connection" ON email_connections FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subject text NOT NULL, body text NOT NULL, status text NOT NULL DEFAULT 'draft',
  total_recipients integer NOT NULL DEFAULT 0, sent_count integer NOT NULL DEFAULT 0, error_count integer NOT NULL DEFAULT 0,
  last_error text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "owner_campaigns" ON campaigns;
CREATE POLICY "owner_campaigns" ON campaigns FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS campaign_sends (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, recipient_email text NOT NULL,
  recipient_name text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'pending', error_message text NOT NULL DEFAULT '',
  sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE campaign_sends ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "owner_campaign_sends" ON campaign_sends;
CREATE POLICY "owner_campaign_sends" ON campaign_sends FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_campaign_sends_campaign_email ON campaign_sends(campaign_id, recipient_email);
CREATE INDEX IF NOT EXISTS idx_campaigns_user_created ON campaigns(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaign_sends_campaign ON campaign_sends(campaign_id, status);
